org.gradle.jvmargs=-Xmx3G

minecraft_version=1.21.11

archives_base_name=smoothswapping
mod_version=0.9.8
maven_group=dev.shwg
artifact_type=beta

#Fabric
fabric_loader_version=0.18.1
fabric_api_version=0.139.4+1.21.11
modmenu=17.0.0-alpha.1

#NeoFroge
forge_version=21.11.0-beta

#Upload configs
curseforge_id=513689
modrinth_id=ydZic5r4
supported_versions=1.21.11