org.gradle.jvmargs=-Xmx3G

minecraft_version=26.1
enabled_platforms=fabric,neoforge

archives_base_name=smoothswapping
mod_version=0.9.9
maven_group=dev.shwg
artifact_type=beta

#Fabric
fabric_loader_version=0.18.5
fabric_api_version=0.144.1+26.1
modmenu=18.0.0-alpha.7

#NeoFroge
forge_version=26.1.0.1-beta

#Upload configs
curseforge_id=513689
modrinth_id=ydZic5r4
supported_versions=26.1