org.gradle.jvmargs=-Xmx3G
yarn_mappings=1.21.3+build.2
yarn_mappings_patch_neoforge_version = 1.21+build.4

minecraft_version=1.21.3

archives_base_name=smoothswapping
mod_version=0.9.4.1
maven_group=dev.shwg
artifact_type=beta

#Fabric
fabric_loader_version=0.17.3
fabric_api_version=0.114.1+1.21.3
modmenu=12.0.0

#NeoFroge
forge_version=21.3.93

#Upload configs
curseforge_id=513689
modrinth_id=ydZic5r4
supported_versions=1.21.2,1.21.3